name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
    # コミットメッセージやPRタイトルから推測
    collapse-after: 15
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📝 Other Changes' # ← ラベルなしのPR用
    labels:
      - '*'

autolabeler:
  - label: 'feature'
    title:
      - '/feature/i'
      - '/component/i'
      - '/create/i'
  - label: 'fix'
    title:
      - '/fix/i'
      - '/bug/i'
  - label: 'chore'
    title:
      - '/document/i'
      - '/refactor/i'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes
  $CHANGES